### ISSUE TITLE
Review API: user-profiles (POST/GET)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#100]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* Ein User-Profile anzulegen (POST)
* Sich alle Profile anzeigen zu lassen (ggf. auch mit Pagination) (GET).

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/97eb79d8-5eea-4548-a1b6-340d5e053d57)

# Verantwortlichkeiten
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
To clarify: Do we need the POST API? Users are created via events. Also user creation still needs more validation/testing and probably a revision. Do we need the GET API for all profiles?

**Comment by Chris-Sauer** [comment]
The GET API for all profiles and the user creation were planned and implemented before the "Event" system. If this is now all handled by events we may also remove the GET All and user creation form the user-service.

**Comment by LPhD** [comment]
Feedback from MLS: Post and Get are not necessary, as indicated by the dashed lines. Post is handled via Events, Get is maybe usefull in the future (but not in its current form).

**Comment by Elscha** [comment]
Entscheidung vom 9.4.2024 mit Eugen & Florian: UserProfile enthählt nur stauts (active/inactive) Sub-DTOs sollen nicht direkt mitgesendet werden. Sub-DTOs (z.B. LearningProfile, CareerProfile, LearningHistory, ...) werden über die gleiche MLS-ID referenziert und müssen im Event-System blanko angelegt werden, wenn auch ein leeres UserProfile angelegt wird.

**Comment by LPhD** [comment]
This should be the new userProfile:
•	Id (MLS id)
•	learningProfile -> Präferenzen des Users, mehr Details s.u.
•	careerProfile -> Job Historie etc., s.u.
•	learningHistory -> Welche Skills wurden wann wie erlernt, etc. (das wird ja nur von uns intern verwendet, richtig?)
•	status (active/inactive)
