### ISSUE TITLE
Review API: user-profiles/{user_profile_id} (GET/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#101]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* Ein User-Profile basierend auf der ID anzeigen zu lassen (GET)
* Ein User-Profile zu *löschen* (auf inaktiv zu setzen, die Daten aber beizubehalten) (DELETE).

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/0bc20577-5385-4d8b-acae-6f2ad7d5537d)

# Verantwortlichkeiten
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
To clarify: Do we still need the actual deletion of user profiles (for administrative purposes)? The MLS DELETE event uses the de-activation (as discussed). Do we still need the DELETE API for user profiles (as mentioned, handled via events)? Why the separation of the two "get" methods?

**Comment by Chris-Sauer** [comment]
From my point of view we still need the "actual" delete for a user-profile, for data protection reasons. If a user insists we need to be able to remove the user/user-profile completely from the system.

**Comment by LPhD** [comment]
Feedback from MLS: Delete Endpoint is not necessary. Get Endpoint is used/required.
