### ISSUE TITLE
Review API: career-profiles/{career_profile_id} (GET/PATCH/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#102]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* Ein Career-Profile anzeigen (GET)
* Ein existierendes Career-Profile upzudaten (PATCH)
* Ein Career-Profile zu löschen (DELETE)

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/a0912fa5-0855-4b09-902a-4483852ce8e4)

# Verantwortlichkeiten
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
GET all and GET single are implemented and tested. PATCH only patches simple datatypes, not jobs and qualifications (they have their own API). DELETE is not required/implemented.
