### ISSUE TITLE
Review API: career-profiles (GET/POST)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#103]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* Ein Career-Profile anzulegen (POST)
* Sich ein Career-Profile anzeigen zu lassen (GET)
  - Potentielle Dopplung zu: #102
  - Bitte mit MLS klären ob doppelte Funktion wirklich benötigt wird und falls ja, dann auf dieselbe Service-Funktion aufbauen und Codedopplung vermeiden

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/6debd94e-f30a-402a-b00f-15a3f85ebaec)

# Verantwortlichkeiten
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by Elscha** [comment]
# Entscheidungen vom Gespräch mit Eugen/Florian am 9.4.2024
* jobHistory: Job[]
* professionalIntressts: string[]
* selfReportedSkills: Freitext[] -> Eher für Recommender-System gedacht
* Keine verifiedSkills, das wäre Datendopplung

# Job
* title: string
* startTime: Date (sorty by ascending)
* endTime: Date | null
* <ein weiter Wert, bitte von @LPhD ergänzen>

**Comment by LPhD** [comment]
Job:
•	title: string
•	startTime: Date (sorty by ascending)
•	endTime: Date | null
•	company: string (Name of company, not ID)

**Comment by LPhD** [comment]
GET with id returns complete career profile including children (career_profiles/career_profile_id). GET (career_profiles) returns all career profiles, which can be useful for learning/ai functions. Miro board is updated accordingly. User id is always the same as career profile id (one to one relation).
