### ISSUE TITLE
Review API: career_profile/{career_profile_id}/job_history/{job_id} (PATCH/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#105]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* In einem Career-Profile einen Job zu bearbeiten (PATCH)
  - Im Miro-Board ist PUT angegeben, bisher haben wir aber immer PATCH verwendet, um hervorzuheben, dass einzelne Werte geändert werden und nicht die komplette Ressource ersetzt wird (Partial-Update, siehe auch 1. unter https://byjus.com/gate/difference-between-put-and-patch-request/) 
* In einem Carerr-Profile einen Job herauszulöschen (DELETE)

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/c1685b41-64a9-4fcb-8852-2f1c15822971)

# Verantwortlichkeiten
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
POST (add new job to career profile's job history) / PATCH / DELETE are finished. GET not required.
