### ISSUE TITLE
Review API: career-profiles/{career_profile_id}/qualifications/{qualification_id} (GET/PATCH/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#107]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* In einem Career-Profile eine bereits erworbene Qualifikation zu bearbeiten (PATCH)
  - Im Miro-Board ist PUT angegeben, bisher haben wir aber immer PATCH verwendet, um hervorzuheben, dass einzelne Werte geändert werden und nicht die komplette Ressource ersetzt wird (Partial-Update, siehe auch 1. unter https://byjus.com/gate/difference-between-put-and-patch-request/) 
* In einem Career-Profile eine Qualifikation herauszulöschen (DELETE)
* Falls gewünscht noch ein GET implementieren, bisher nicht der Fall, da dieses von #102 subsumiert wird

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/3e912e60-f10f-41e8-8b6a-17c2c1482186)

# Verantwortlichkeiten
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by Elscha** [comment]
# Entscheidungen vom Gespräch mit Eugen/Florian am 9.4.2024
* title: string
* berufeNetId: Optionale ID aus dem BerufeNet
* date: Date

Speichert die erworbene Qualifikation, optionale mit Referenz zum BerufeNet. Date sollte ein Date-Objekt sein, damit man mehrere Abschlüsse in einem Jahr auch auf einem Zeitstrahl darstellen kann.

Einträge sollten sortiert nach dem Datum (aufsteigend) zurückgegeben werden

**Comment by LPhD** [comment]
POST (add new qualification to career profile) / PATCH / DELETE are finished. GET not required.
