### ISSUE TITLE
Review API: learning-profiles/{learning_profile_id} (GET/PATCH/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#108]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* In sich ein Lern-Profil anzeigen zu lassen (GET)
* Ein Lern-Profil upzudaten (PATCH)
  - Im Miro-Board ist PUT angegeben, bisher haben wir aber immer PATCH verwendet, um hervorzuheben, dass einzelne Werte geändert werden und nicht die komplette Ressource ersetzt wird (Partial-Update, siehe auch 1. unter https://byjus.com/gate/difference-between-put-and-patch-request/) 
* Ein Lern-Profil zu löschen (DELETE)

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/524f1b20-bd63-4b97-add2-e0c8e869e0f6)

# Verantwortlichkeiten
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by Elscha** [comment]
# Entscheidungen vom Gespräch mit Eugen/Florian am 9.4.2024
* semanticDensity: [0; 1]
* semanticGravity: [0; 1]
* mediaType: string[]
* language: string[], nach Isostandard: z.B. de_de
* processingTime: number (Minuten)
* preferredDidacticMethod: string

Präferenzen vom Lernenden.
- Density/Gravity müssen in MLS, SSE-Service, Meta-AI-Service identisch gehandhabt werden. Aktueller Vorschlag Prozentwert von 0 - 100 (als Flot 0-1).
- MediaType: Mehrere präferierte Typen unterstützen. Reihenfolge gibt Priorisierung vor
- Sprachen analog zu Medientypen
- processindTime Präferrierte Länge in Minuten
- preferredDidaticMethod: Prinzip der vollständigen Handlung, Nugget Ensemble

**Wichtig:** In DTO bitte Beispiel für valide Wertebereiche mit angeben.

**Comment by LPhD** [comment]
Delete is not planned/required
