### ISSUE TITLE
Review & Clarify: learning-history/{history_id} (GET/PUT/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#109]
# Beschreibung
Scheinbar handelt es sich um eine alternative API (V1 und gestrichelt). Daher bitte im ersten Schritt mit MLS klären ob das wirklich so zusätzlich gewollt ist und falls ja wie ein Fortsetzen funktionieren soll, wenn eine lernende Person mehr als einen Pfad (Kurs) selektiert hat.

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/084142dd-e5b2-4f23-88ce-d7841e03b275)

# Verantwortlichkeiten
- [x] Klärung mit MLS: @LPhD 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
New specification is in Miro under V2, V1 is obsolete
