### ISSUE TITLE
Review & Clarify: learning-history/{history_id} (POST/GET)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#110]
# Beschreibung
* Klärung: Im POST wird angegeben, dass man direkt erworbene Skills einträgt, bei GET werden gelernte Pfade zurück gegeben. Meiner Meinung nach macht es Sinn, dass:
  - POST legt Sequenz von zu lernenden Units an
  - PATCH ändert deren Status (angefangen, erfolgreich absolviert, ...)
  - GET zeigt Pfade und deren Status an
  - Um mehrere Pfade zu untersützen, benötigt man immer auch eine Pfad ID, auch für manuell eingetragene Pfade
* Nach Klärung die Implementierung

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/345f2e2d-96ed-478a-9f36-a7920f972bf3)

# Verantwortlichkeiten
- [x] Klärung mit MLS: @LPhD 
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Das Datenbank-Schema wurde bereits so angepasst, dass zu einer Lerneinheit der Bearbeitungsstatus angepasst werden kann (`ConsumedUnit`)
  - Eine `ConsumedUnit` kann entweder direkt (z.B. über direkte Suche) oder über Lernpfade gelernt werden (z.B. vorgegebener Pfad/Kurs oder ebenfalls eine Suche die mehr als eine Unit enthält um Ziel zu lernen).
  - Für einen Pfad kann die Reihenfolge der Units gespeichert werden `PathSequence`
  - Erklärung des Schemas unter: https://github.com/e-Learning-by-SSE/nm-skill-service/blob/fix/LearningHistory/prisma/schema.prisma#L302-L323
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
The learningHistory itself has no API, only the contained learnedSkills and personalizedLearningPaths. The history is created together with its user. Updates to its children happen via events. Child content is received via dedicated GET APIs. Delete is not required.
