### ISSUE TITLE
Review & Clarify: learning-history/{history_id}/{com_path_id} (GET/PATCH/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#111]
# Beschreibung
Review und ggf. Implementierung, dass:
* Ein Pfad angezeigt werden kann (GET)
* Ein Pad editiert werden kann (PATCH), unklar (ggf. klären):
  - Muss nur der Status von gelernten `ConsumedUnits` geändert werden können
    * Kann der Status auch degradiert werden? Können als bereits absolvierte `ConsumedUnits` auf `Open` oder `Started` zurückgesetzt werden?
  - Muss auch der Pfad angepasst werden?
* Ein Pfad kann gelöscht werden (POST)

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/ecaac01b-43df-4891-8629-851eb7ae6ad9)

# Verantwortlichkeiten
- [x] Klärung mit MLS: @LPhD 
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Es gibt bereits Funktionen um einen Pfad in der DB anzulegen und den Status von `ConsumedUnits`zu ändern: https://github.com/e-Learning-by-SSE/nm-skill-service/blob/fix/LearningHistory/src/user/learningHistoryService/learningHistory.service.ts#L88-L165
* Das Datenbank-Schema wurde bereits so angepasst, dass zu einer Lerneinheit der Bearbeitungsstatus angepasst werden kann (`ConsumedUnit`)
  - Eine `ConsumedUnit` kann entweder direkt (z.B. über direkte Suche) oder über Lernpfade gelernt werden (z.B. vorgegebener Pfad/Kurs oder ebenfalls eine Suche die mehr als eine Unit enthält um Ziel zu lernen).
  - Für einen Pfad kann die Reihenfolge der Units gespeichert werden `PathSequence`
  - Erklärung des Schemas unter: https://github.com/e-Learning-by-SSE/nm-skill-service/blob/fix/LearningHistory/prisma/schema.prisma#L302-L323
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
The computed path is now renamed to personalizedLearningPath and contains the LearningUnitInstances (previously consumedUnits). Updates happen via events. All paths (filterable by state, ordered descending by updatedAt property) or a single one can be retreived via a GET request. Delete is not required.

**Comment by LPhD** [comment]
Creation and updating personalized pathes still needs to be done (and requires additional test cases).
