### ISSUE TITLE
Review & Clarify API: learning-behavior-data/{behavior-id} (GET/PATCH/DELETE)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#113]
# Beschreibung
Review und falls nötig fehlende Funktionen implementieren um:
* Learning-Behavior zu bearbeiten (PATCH)
  - Im Miro-Board ist PUT angegeben, bisher haben wir aber immer PATCH verwendet, um hervorzuheben, dass einzelne Werte geändert werden und nicht die komplette Ressource ersetzt wird (Partial-Update, siehe auch 1. unter https://byjus.com/gate/difference-between-put-and-patch-request/) 
* Learning-Behavior zu löschen (DELETE)
* Learning-Behavior anzeigen zu lassen (GET)

# Klärungsbedarf
* Es muss noch geklärt werden, was dazu gespeichert werden soll. Insbesondere was sind Click Data?
* Derzeit sind die Verhaltensdaten an den `ConsumedUnits` angehängt (Bearbeitungszeit, Performanz, und Lernverhalten`: https://github.com/e-Learning-by-SSE/nm-skill-service/blob/fix/LearningHistory/prisma/schema.prisma#L357-L361
  - Soll das so bleiben? Pro: Individuelle Messergebnisse pro Einheit, Con: Ggf. problematisch bei der Agregation
  - Wenn es so bleibt, wird wirklich eine separate Tabelle pro `ConsumedUnit` für die LearningBehavior benötigt, welche im wesentlichen nur einen Wert speichern (Click Data) oder kann dieser Wert auch in die `ConsumedUnit` integriert oder gar ganz gestrichen werden?

![Image](https://github.com/e-Learning-by-SSE/nm-skill-service/assets/6489033/818bdfb8-95fe-4d35-80aa-71ea8e3be767)

# Verantwortlichkeiten
- [x] Klärung: @LPhD 
- [x] Code Review / Functional completness: @LPhD 
- [x] Testfälle: @Chris-Sauer 

# Hinweise
* Aktueller Code für das User-Profile befindet sich in Branch: [fix/LearningHistory](https://github.com/e-Learning-by-SSE/nm-skill-service/tree/fix/LearningHistory)
* API Disskusion mit MLS über: https://miro.com/app/board/uXjVMkWeDEY=/

**Comment by LPhD** [comment]
Is no longer required, as discussed with MLS on 09.04.2024
