### ISSUE TITLE
Ungenutzte Feature Branches Löschen

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#23]
Bitte prüft welche Feature Branches ihr angelegt hattet, bereits integriert wurden, nicht mehr benötigt werden und somit [gelöscht](https://github.com/e-Learning-by-SSE/nm-concept/blob/main/doc/BRANCHING.md#Delete-Feature-Branch) werden können. Kandidaten sind meiner Meinung nach:
* CRUDRepo
* 7-learningprogress-skills
* 13-adaption-of-user-service
* 12-adaption-off-learning-unit-endpoint-to-requirements-from-250923

**Comment by WenzelSSE** [comment]
7, 12, CRUD Repo gelöscht

**Comment by Chris-Sauer** [comment]
13-adaption-of-user-service Branch gelöscht
