### ISSUE TITLE
API Skill Repositories Verwalten (CRUD)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#3]
In `nm-skill-service` prüfen das die folgenden Funktionen vollständig umgesetzt wurden und wenn nötig verfollständigen:
- **POST** skill-repositories/ für das Anlegen eines SkillRepositories. 
  - [x] Implementiert
  - [x] Vollständig getestet

- **GET** skill-repositories/byOwner/{ownerId} für die Abfrage aller Skill Repositories. Der Owner ist eine vom Client bestimmbare Id, die ich beim POST angelegt habe. 
  - [x] Implementiert
  - [x] Vollständig getestet

- **GET** skill-repositories/byId/{repositoryId} für die Abfrage eines SkillRepositories basierend auf der SkillRepository Id von euch
  - [x] Implementiert
  - [x] Vollständig getestet

- **DELETE** skill-repositories/{repoId}/del für das Löschen eines Skill-Repositories. Ist Äquivalent mit der Löschung aller Skills aus einem Repository. Mit Außnahme, dass nichts gelöscht wird, sofern eine Löschung innerhalb der Kette nicht durchgeführt werden kann. Werden alle SkillsRepos eines Owners gelöscht, kann der Owner mitgelöscht werden, sofern ihr den dann noch irgendwo trackt. 
  > **Klärungsgedarf:** Skill repository soll gelöscht werden insofern nicht irgendwoin der Kette was nicht gelöscht werden kann, soll aber gleichzeitig equivalent zum Löschen aller Skills sein. => Alle Skills löschen, insofern diese in keinen LearningUnits verwendet werden?
  - [x] Implementiert
  - [x] Vollständig getestet

- **PUT** skill-repositories/ sollte es auch geben. 
  - [x] Implementiert
  - [x] Vollständig getestet

### Jeweils pro Endpoint:
- Implementierung der gewünschten Funktionalität im Service und Bereitstellung im Controller
- End 2 End Tests, welche sowohl positive Fälle (z.B. erfolgreiches Löschen) als auch negative Fälle testen. Sollte es mehrere kombinatorische Möglichkeiten geben, auch diese testen
- Beim **PUT** sollten außerdem immer nur Werte überschrieben werden, die auch mitgeliefert wurden. Der Rest sollte erhalten bleiben. 
Generell braucht nichts resolved werden. Die Rückgabe der jeweiligen IDs reicht. 
Wie die Endpoints genau heißen, ist dabei jetzt nicht so wichtig, hauptsache ein Endpoint wird nicht für mehrere Sachen genutzt.

**Comment by WenzelSSE** [comment]
POST skill-repositories/ für das Anlegen eines SkillRepositories. 
-> unter dem Pfad existiert bereits eine Methode, soll die erhalten bleiben?
Wenn ja würde ich skill-repositories/create/ als Endpoint vorschlagen

**Comment by WenzelSSE** [comment]
PUT skill-repositories/ sollte es auch geben.

hier wieder ein Konflikt im der Benennung des Pfades 
mein Vorschlag hier 
skill-repositories/adapt

**Comment by WenzelSSE** [comment]
DELETE skill-repositories/{repoId}/del für das Löschen eines Skill-Repositories. Ist Äquivalent mit der Löschung aller Skills aus einem Repository. Mit Außnahme, dass nichts gelöscht wird, sofern eine Löschung innerhalb der Kette nicht durchgeführt werden kann. Werden alle SkillsRepos eines Owners gelöscht, kann der Owner mitgelöscht werden, sofern ihr den dann noch irgendwo trackt

Wie soll denn das tracking umgesetzt werden? Aktuell gibt es kein Tracking, ein Owner gibt es nur als Eintrag in der DB am jeweiligen Skill Repo. Vermutlich kam daher auch die Verworfene Änderung im Anforderungsdiagramm. 

Lösungsvorschlag Objekt "externer User" erzeugen inkl. DB Einträgen. Diese können dann Repos haben oder halt nicht.

**Comment by Elscha** [comment]
Prinzipiell wären gemäß REST
`POST skill-repositories` und `PUT skill-repositories` zwei echte Endpunkte, die von NestJS als unterschiedliche Endpunkte unterstützt werden und von anderen REST-Frameworks ebenfalls unterstützt werden können sollten. Bei Florians Aussage, dass nicht ein Endpunkt für zwei unterschiedliche Sachen verwendet werden sollten, ging es wohl um einen Fehler den ich in einer früheren Version übersehen hatte:
`GET skill-repositories/{repositoryId}` und `GET skill-repositories/{ownerId}`, dass ist faktisch 2 Mal derselbe Endpunkt für zwei unterschiedliche Funktionalitäten und konnte so auch nicht gehen. Sowas sollte sowieso vermieden werden.

Des Weiteren war Florians Aussage: _"Wie die Endpoints genau heißen, ist dabei jetzt nicht so wichtig, Hauptsache ein Endpoint wird nicht für mehrere Sachen genutzt."_
Dem entsprechend bittte Entpunkte wie folgt umsetzen:
- Bei bisherigen Endpunkten prüfen ob es einen Konflikt gibt, falls ja beheben, andernfalls belassen
- Bei neuen Endpunkten prüfen was eine gute URI wäre, versuchen hier ein einheitlichen Namensschema zu etablieren (adapt, create, del, ..., generelle Kleinschreibung in den Pfaden, ....) und dann anlegen. Falls die oben genannten Vorschläge dann so nicht passen, entsprechend anpassen.
- Sollten sich Endpunkte ändern, bitte die Version gemäß Semantic Versioning (https://semver.org/lang/de/) anpassen:
  - Bei Umbennenung, Löschung vorheriger Endpunkte -> Minor Version anpassen (z.B. 0.6.x -> 0.7.0)
  - Bei Ergänzungen -> Patch Version Anpassen (z.B. 0.6.3 -> 0.6.4)

**Comment by Elscha** [comment]
Zum Löschen eines Owners. Ich vermute, dass hier ein Missverständnis auf Florians-Seite vorliegt. Insofern es bei der Entwicklung berücksichtigt werden muss, kann man ihn an einem der Montags-Meetings nochmal nachfragen:
- Zunächst hängen die Repositories nur an einer ID (`owner`), welche vom MLS-System genutzt wird um dort Benutzer zu identifizieren. Wird ein Repository gelöscht und gibt's zu der ID keine weiteren Repositories, ist der Owner auch faktisch in unserem Webservice gelöscht. Ob MLS diese auch in ihrer DB entfernen will, müssen sie selbst entscheiden. Aussage von Florian war, dass die SEARCH-Erweiteruneng minimal in deren System integriert werden sollen, so können wir eine solche Business-Logik auch gar nicht für sie implementieren.
- Was theoretisch vorkommen kann. Ein Benutzer des MLS-Systems ist sowohl Content-Creator (erstellt Repositories) und auch Lernender (verwendet ein Lernenden-Profil). Nur weil wir das letzte Repository von dem Benutzer löschen, würde ich nicht auch gleich seine Lern-Historie löschen wollen, wo es ohnehin dafür separate Endpunkte geben werden muss.

**Comment by WenzelSSE** [comment]
Functionality implemented as described, test also 95%, but because we are currently refining the functions and endpoints, the task is marked as complete.

For the new requirements these would have to be in new ticket?

**Comment by Elscha** [comment]
Yes: New tickets for new requirements.
