### ISSUE TITLE
API Skills Verwalten (CRUD)

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#4]
- **GET** skill/{skillId} für die Abfrage an einen Skill basierend auf der Skill-Id von euch, hierbei sollen sowohl parents wie auch children (nestedSkills) des Skills angegeben werden. 
  - [x] Implementiert
  - [x] Vollständig getestet

- **POST** skill/ zum Anlegen eines neuen Skills mit Kinder (nestedSkills), welche angegeben werden durch ein Array aus Ids der Skills, die Kinder sein sollen. 
  - [x] Implementiert
  - [x] Vollständig getestet

- **DELETE** skill/{skillId}/del für das Löschen eines Skills. Sollte nicht erlaubt werden, wenn der Skill bereits irgendwo anders verwendet wird. Sollte aber erlaubt sein, wenn der Skill Kinder hat. In diesem Fall sollen auch alle Kinder mitgelöscht werden, sofern erlaubt. Ist irgendwas in der Kette der Löschungen nicht erlaubt, soll nichts gelöscht werden (Atomarität jeder Transaktion bewahren) und es soll ein 400er-Fehler geworfen werden.
  - [x] Implementiert
  - [x] Vollständig getestet

- **PUT** skill/{skillId}/adapt . Es soll die Möglichkeit geben Skills zu modifizieren. Hier sind erstmal keine Versionen notwendig, denn das soll auch hier erstmal nur erlaubt sein, wenn der Skill nirgends verwendet wird. (In dem Fall würdet ihr ja auch keine neue Version anlegen wollen, oder?). Dabei kann ich die Kinder des Skills festlegen durch Angabe der nestedSkills. Dabei werden Ids der Skills angegeben. Existieren die Skills nicht oder würde die Eltern-Kind-Beziehung zu einem Zyklus führen, schlägt die Transaktion fehl (mit 400er antworten) und es soll nichts verändert werden (Atomarität jeder Transaktion bewahren). 
  - [x] Implementiert
  - [x] Vollständig getestet

- **GET** /skill-repositories/showAllSkills . Es sollen alle Skills samt parents und nestedSkills in einer Liste ausgeben werden 
  - [x] Implementiert
  - [x] Vollständig getestet
  
### Jeweils pro Endpoint:
- Implementierung der gewünschten Funktionalität im Service und Bereitstellung im Controller
- End 2 End Tests, welche sowohl positive Fälle (z.B. erfolgreiches Löschen) als auch negative Fälle testen. Sollte es mehrere kombinatorische Möglichkeiten geben, auch diese testen
- Beim **PUT** sollten außerdem immer nur Werte überschrieben werden, die auch mitgeliefert wurden. Der Rest sollte erhalten bleiben. 
Generell braucht nichts resolved werden. Die Rückgabe der jeweiligen IDs reicht. 
Wie die Endpoints genau heißen, ist dabei jetzt nicht so wichtig, hauptsache ein Endpoint wird nicht für mehrere Sachen genutzt.

**Comment by WenzelSSE** [comment]
Functionality implemented as described, test also 95%, but because we are currently refining the functions and endpoints, the task is complete. 

For the new requirements these would have to be in new ticket?

**Comment by Elscha** [comment]
Yes: New tickets for new requirements.
