### ISSUE TITLE
Lern-Historie: Service / Keine API

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#44]
# Anforderung
Für e-Learning-by-SSE/nm-skill-service#43 wird ein neues Modul mit min. zwei neuen Tabellen + ein Service benötigt:
- Eine Tabelle zum Abspeichern, dass ein neuer Pfad vom User ausgewählt wurde. Folgende Daten werden benötigt:
  - ID des Pfades
  - User-ID (Reference zu MLS), welcher User sich den Pfad angelegt hat
  - Lifecycle (unvollständig): Ausgewählt (STARTED), Berbeitung begonnen (IN PROGRESS), Berarbeitung beendet (FINISHED), gelöscht (DELETED), ...
  - Kritierien für die Wahl des Pfades (zur Reproduzierbarkeit) -> Unklar
  - ...
- Eine Tabelle, die den Lernfortschritt speichert. Es wird zu jeder Lerneinheit des Pfades ein Eintrag erstellt, mit folgenden Werten
  - Pfad_ID (Referenz zur vorherigen Tabelle)
  - ID zu Lerneinheit
  - Bearbeitungsstatus (unvollständig, unklar ob Prozentwert oder Enum besser): Unbearbeitet (OPEN), Bearbeitet aber noch nicht abgeschlossen z.B. weil Quiz noch nicht bearbeitet wurde (STARTED), Abgeschlossen (FINISHED)
  - Datum wann beendet? -> Klärung mit Carsten / Chris ob es für User-Profil sinnvoll ist
  - ... 

# Aufgaben
- [x] Anlegen der Tabellen
- [x] Initiale Funktion um Lernpfad anzulegen (zunächst nur Angabe der Lerneinheiten notwendig), legt Tabelle für Pfad und Tabelle für Bearbeitungsstatus der Lerneinheiten an
- [x] Funktion um für einen User den Status einer Lerneinheit zu editieren (müsste vermutlich die Lerneinheit in allen Pfaden verändern, insofern diese in mehreren Pfaden vorhanden ist)
- [x] Funktion, welche den Status einer jeden Lerneinheit für einen Pfad zurück gibt. So könnte in der UI der Progress als Outline dargestellt werden (Pfad anzeigen + highlighten was bereits bearbeitet wurde und was noch offen ist).
- [x] Testfälle, aber zunächst kein Controller und damit keine E2E Tests

**Comment by Elscha** [comment]
Beschlossen wurde eine neue Tabellen Aufteilung in 3 Tabellen, dabei dient die bereits existierende `LearningHistory` als gemeinsamer Einstiegspunkt / Obertabelle:
* Die bereits existierende `ConsumedUnitData` wird erweitert, so dass sie unabhängig von einem Lernpfad abspeichert, welche LearningUnits bereits von einem User (teilweise) bearbeitet wurden. Ggf. wird da auch der Bearbeitungszeitpunkt abgespeichert. Z.B.:
| unit_id | status | date | ... |
* Ebenfalls als Teil der `LearningHistory` wird eine neue Tabelle angelegt, welche die Metadaten zu abgespeicherten Lernpfaden abspeichert. Z.B.:
| path_id | user_id| ... |
* Für einen Lernpfad werden dann die gewählten Lerneinheiten und die Reihenfolge, aber nicht der Bearbeitungsstatus in einer neuen Tabelle abgespeichert. Z.B.:
| path_id | position | unit_id | 

Über einen Join können dann für einen Pfad die Reihenfolge der Lerneinheiten und der Bearbeitungsstatus herausgesucht werden.

Note: Ggf. kann später der Reihenfolge wieder entfernt werden, wenn wir über die PFadmetadaten + Algorithmus den Pfad sicher reproduzieren können.

**Comment by WenzelSSE** [comment]
^^wird als eigenes Ticket realisiert -> Ticket #47
