### ISSUE TITLE
Adaption of UserService to spec in miro board

### ISSUE THREAD

**Issue by WenzelSSE** [e-Learning-by-SSE/nm-skill-service#46]

**Comment by WenzelSSE** [comment]
![Uploading Screenshot 2023-11-10 at 10.35.43.png…]()

**Comment by WenzelSSE** [comment]
<img width="1229" alt="Screenshot 2023-11-10 at 10 35 56" src="https://github.com/e-Learning-by-SSE/nm-skill-service/assets/111048980/4899c050-bfbd-4ace-8ac9-9614e9b70fd9">

**Comment by WenzelSSE** [comment]
<img width="1293" alt="Screenshot 2023-11-10 at 10 35 43" src="https://github.com/e-Learning-by-SSE/nm-skill-service/assets/111048980/2ecd46e5-7a06-4d40-8c35-45e86a64e486">

**Comment by WenzelSSE** [comment]
<img width="1229" alt="Screenshot 2023-11-10 at 10 35 56" src="https://github.com/e-Learning-by-SSE/nm-skill-service/assets/111048980/1acffb08-4f0f-447e-a3bd-2d7c7e4bec92">

**Comment by Elscha** [comment]
Wie ist der aktuelle Stand, was fehlt noch um das endlich abzuschließen?

**Comment by Elscha** [comment]
Task is running for to long (Nov'23 - Mar'24) without notable progress -> I will reorganize this issue
