### ISSUE TITLE
API: Lernfortschritt

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#5]
Erstellung einer API (CRUD) in `nm-skill-service` zum Verwalten einer Lernhistorie, als Bestandteil des `LearningProfile`. Dabei sollten bereits erworbene Skills gespeichert werden.
Optional können weitere Daten gesammelt werden, insofern diese für die Erstellung eines Learnenden-Profils als Sinnvoll erscheinen:
* Wann wurde Skill erworben (ggf. aufgefrischt), alls man einbauen möchte, dass Skills auch wieder verlernt werden können
* Erworbene LearningUnits (vermutlich eher an einer anderen stelle im Lernenden Profil)

Konkret geht es um die MLS Historie aus dem August'23 Diagramm, welche bislang ein Erwerb von Fähigkeiten auf Basis von Learneinheiten vorsieht:
![Image](https://user-images.githubusercontent.com/6489033/265913278-badb19ab-a3ba-440e-86a4-c68251aea858.png)

### Bestandteile
- [x] Erweiterung der Datenbank über das Prisma Schemas
- [x] Anlegen von Controllern, welche die Endpunkte bereitstellen
- [x] Anlegen von Data Transfer Objects (DTOs), welche als Datenobjekte zwischen den Prozessen (Services) dienen
- [x] Implementierung des Services, welcher die Logik umsetzt
- [x] Ggf. anlegen eines Moduls, welcher Service und Controler verwaltet
- [x] Erstellung von Testfällen, welche die Logik des Services testen
- [x] Ggf. Erstellung von End 2 End tests, welche das korrekte Verhalten (Antworten) der Controller testen

### Endpunkte
Genauer Pfad noch unklar, Vorschlag: `/users/learning-progress/`
- **GET** /users/learning-progress/{userId} Für die Abfrage des Lernfortschritts für einen onrekten User. Dabei stammt die ID aus dem MLS-System
> Klärungsbedarf (mit Florian): Was soll bei nicht vorhandener ID returned werden? Soll ein neues, leeres Profil erstellt werden. oder eine 400er Fehlermeldung zurück gegeben werden? Gemäß REST wäre eine 400er Meldung die saubere Variante

- **POST** /users/learning-progress/{userId} erstellt ein neues, leeres Profil für einen User. Die ID stammt aus dem MLS System.
- **DELETE** /users/learning-progress/{userId}/del löscht ein Profil eines Users. Die ID stammt aus dem MLS System.
> Klärungsbedarf (mit Florian / Christian): Wann kann der LErnfortschritt gelöscht werden?
  - Christian: Kann der Lernfortschritt auch ohne restliches User-Profil gelöscht werden, oder löschen wir das nur als Gesamtpaket?
  - Florian: Wann/welche Implikationen hängen an der Löschung. Müssen auf MLS-Seite Voraussetzungen erfüllt sein (z.B. keine offenen Lernfortschritte, ...)?

- **PUT** /users/learning-progress/{userId}/adpt Zum Hinzufügen (und Löschen?) absolvierter Skills (Lerneinheiten).

Generell gilt:
Beim **PUT** sollten außerdem immer nur Werte überschrieben werden, die auch mitgeliefert wurden. Der Rest sollte erhalten bleiben.

**Comment by LPhD** [comment]
Implemented via learningProfile (preferences) and learningHisotry (learned Skills and personalizedLearningPaths containing concrete learningUnitInstances with additional information, like processingTime, state, and updatedAt)
