### ISSUE TITLE
SkillProfile umbenennen

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#6]
Gemäß Analysediagramm gibt es ein _SkillsProfile_

![Image](https://user-images.githubusercontent.com/6489033/266906162-b91ce9d1-082f-46b9-9fba-791b717c0dec.png)

dieser Name ist aber recht unglücklich gewählt, da _Skills_ bereits ein zentrales Konzept des Skill-Repositories darstellen, wodurch es während der Entwicklung schnell zu Verwirrungen kommen kann. Daher sollte das _SkillsProfile_ intern (vor allem das Prisma-Schema) in etwas sprechenderes umbenannt werden. Da es hier um die berufliche Laufbahn des Lernenden geht, würde ich empfehlen etwas in der Richtung zu wählen:
- CareerProfile
- ProfessionalCareer
- ProfessionalsProfile
- ...

**Comment by Chris-Sauer** [comment]
Renamed the SkillProfiles to CareerProfiles

**Comment by Chris-Sauer** [comment]
Renamed the SkillProfiles to CareerProfiles
