### ISSUE TITLE
Error: EACCES: permission denied, mkdir './logs/'

### ISSUE THREAD

**Issue by WenzelSSE** [e-Learning-by-SSE/nm-skill-service#91]
There is currently a problem with the build on Jenkins, where the path for the logs cannot be created. 
According to Marcel, the problem here is a lack of authorizations, which can be solved by changing the Dockerfile

Hint: 
# Create the directory path
RUN mkdir -p /nm-skill-service/logs

something similar to this may fix the issue

**Comment by Elscha** [comment]
Fixed in 98394a45c3308c8f179a99e72d0e9d2327140264
