### ISSUE TITLE
User-Profile: Refaktoring

### ISSUE THREAD

**Issue by Elscha** [e-Learning-by-SSE/nm-skill-service#94]
Das User-Profile bündelt viele verschiedene Funktionen, für die gemäß der Anforderungen im Miro-Board (https://miro.com/app/board/uXjVMkWeDEY=/) viele Endpoints im ```UserMgmtController``` bereit gestellt werden. Dies sind Funktionen zu:
- User-Profile
- LearningHistory
- CareerProfile
- JobProfile

was so auch in Ordning ist.

Dem gegenüber steht nur ein Service, der ```UserMgmtService```, welcher sich ebenfalls dieser 3-4 _Anliegen_ annimmt und entsprechend rund 1.000 Zeilen Code umfasst, wodurch dieser sehr unübersichtlich geworden sind. Gemäß des SE-Prinzips _"Separation of Concerns"_ sollte dieser Service in 3-4 Services unterteilt werden, die alle im Controller aufgerufen werden können:
* Ein Service für das User-Profile, kann falls nötig die anderen Services mit aufrufen
* Ein Service für die Lern-Historie
* Ein Service für das Karriere-Profil
* Ein Service für den aktuellen Job. Falls zwischen Job und Karriere eine starke Bindung existiert (z.B. weil diese immer zusammen geupdatet werden müssen), können diese beiden auch weiterhin in einem gemeinsamen Service realsiert werden.

Zudem sind mir bei der Durchsicht des Codes einige Rechtschreibfehler aufgefallen, welche auch gleich korrgiert werden können (bei der Gelegenheit bitte prüfen, ob das empfohlene Plug-in ```code-spell-checker``` auch tatsächlich installiert und eingeschaltet ist). Unter anderem waren es:
* Profil (Profile ohne e)
* JobsNet (BerufeNet ist Eigenname)
* In der Datenbank die Tabelle Beruf (im englischen Job)
* qualificaion
* Hisory

**Comment by Chris-Sauer** [comment]
Korrektur des Codes: 

Branch "94-user-profile-refaktoring" rebased auf main.

Folgende Schreibweisen korregiert:

    Profil (Profile ohne e)
    JobsNet (BerufeNet ist Eigenname)
    In der Datenbank die Tabelle Beruf (im englischen Job)
    qualificaion
    Hisory
    korrektes camelcasing für starttime, endtime, jobtitle

abgeschlossen und getestet im Branch "94-user-profile-refaktoring", Branch aktualisiert.

All „Profil“ ammended to „Profile“

JobsNet (BerufeNet ist Eigenname):
„jobIdAtBerufeNet“ ammmended to  „jobIdAtJobsNet“

In der Datenbank die Tabelle Beruf (im englischen Job):
“Beruf” changed to  “JobDescription”    // “Job” was already in use in the DB

All “qualificaion” amended to “qualification”

All “Hisory” amended to “History”

Used proper camelcasing for:
“starttime” amended to “startTime”,
“endtime” amended to “endTime”,
“jobtitle” amended to “jobTitle

As the Prisma schema was changed, this needs to be re-generated

**Comment by Elscha** [comment]
Änderungen beziehen sich auf 7515b0470a996e34738fea14e94ab52adb9b9b7f

Folgende Anmerkungen:
- Da BerufeNet ein Eigenname ist, sollte der Name auch im Englischen beibehalten werden. Also z.B. wäre `jobsAtBerufeNet` OK.
- Die Package.json sollte nicht ohne Absprache angepasst werden. Insbesondere sollte kein Downgrade von verwendeten Bibliotheken durchgeführt werden. Der angegebene Commit downgraded den Prisma Client von 5.6.0 auf 5.3.1. Diese Änderung bitte wieder rückgängig machen
- Migrationen sollten auch nur bei Erstellung eines Releases gemacht werden und nicht in den Feature-Branches. Diese bei Bedarf bitte löschen, ansonsten werde ich es später beim Merge in den Main machen.

**Comment by Elscha** [comment]
Zudem fehlt der wichtigste Punkt des Refaktorings: Der UserService sollte in 3-4 Services zerteilt werden:
- User-Service
- CareerProfile-Service
  - Evtl. JobProfile-Service
- LearningHistory-Service

**Comment by LPhD** [comment]
Done and merged in main.
